### ISSUE TITLE
Custom shape on the front layer

### ISSUE THREAD

**Issue by milkyway044** [fluttercommunity/backdrop#115]
It would be nice to be able to change the shape of the front layer. I have a design with beveled corners like in [Shrine Material theme](https://material.io/design/material-studies/shrine.html#shape), but now there is no way to change shape.

![Shrine's customized backdrop](https://lh3.googleusercontent.com/jcZK7YBo1KPvMhq27jah-6zjmNse-FgZGTs3Pw9T154bipVfkvudyq80yUw-9IS2mlI7S-3Y1SYSA2YCtViPGsPbQ5S_q1iAE097cg=w1064-v0)

![The front layer of Shrine's backdrop uses a custom cut corner on the top left, giving the backdrop an asymmetrical shape.](https://lh3.googleusercontent.com/WuZ91HKN8HulF57V0samfU-mfex1Yt_2R9JRRp9NLrfbLqTSzpfHEA1zQlt_BN3vlnLyMsq7ml3rUTh1O2iWzjkZn6k9q_ymTbO8cbg=w1064-v0)

**Comment by milkyway044** [comment]
[https://material.io/components/backdrop#theming](https://material.io/components/backdrop#theming)

**Comment by daadu** [comment]
@WieFel I am surprised that this is not being implemented!

Should we generalise `frontLayerBorderRadius` to `frontLayerShape` ?? Or keep both?

I am in favour of only having `frontLayerShape` and deprecating `frontLayerBorderRadius`.

**Comment by daadu** [comment]
Looks non-trivial to just replace. `frontLayerBorderRadius` is used to "clip" as well - maybe to show scrim properly.

Check this code:

https://github.com/fluttercommunity/backdrop/blob/e623fb85a904035247e766b24faea80d8f198fac/lib/src/scaffold.dart#L544-L551

**Comment by daadu** [comment]
Ok, looks like we can do it "clipping" based on `ShapeBorder` with `ShapeBorderClipper`

**Comment by daadu** [comment]
@milkyway044 Request you to review and test against the PR for this feature.

**Comment by WieFel** [comment]
> @WieFel I am surprised that this is not being implemented!

Me too actually!

> Should we generalise `frontLayerBorderRadius` to `frontLayerShape` ??

Yes LGTM

**Comment by milkyway044** [comment]
> @milkyway044 Request you to review and test against the PR for this feature.

@daadu this is exactly what i need, thank you so much, guys!
