### ISSUE TITLE
Demo site of the package hosted as Github Pages

### ISSUE THREAD

**Issue by daadu** [fluttercommunity/backdrop#12]
**Is your feature request related to a problem? Please describe.**
Could be used to quickly see what the package can do and interact with it.

**Describe the solution you'd like**
build example for flutter web and host it as Github pages.

**Comment by daadu** [comment]
- Possibly should be triggered with Github Actions
- Possible should have option to toggle between screen sizes - `mobile`, `tablet` and `desktop`

**Comment by daadu** [comment]
Requested for Github Pages setting https://github.com/fluttercommunity/community/issues/55

**Comment by daadu** [comment]
Demo app hosted at https://github.com/fluttercommunity/backdrop/demo

**Comment by WieFel** [comment]
@daadu small side note: I get 404 when opening https://github.com/fluttercommunity/backdrop/demo

**Comment by daadu** [comment]
Oops!! updated the link.
