### ISSUE TITLE
flutter beta: SchedulerBinding is now null-safe

### ISSUE THREAD

**Issue by mockturtl** [fluttercommunity/backdrop#122]
**Describe the bug**

Build warning with Flutter beta channel (`2.13.0-0.2.pre`):

```sh
./../../.pub-cache/hosted/pub.dartlang.org/backdrop-0.7.1/lib/src/scaffold.dart:687:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which
excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback((_) => _notify());
```

The fix is trivial.  PR incoming.

**Additional context**

Upstream change:

- https://github.com/flutter/flutter/blame/master/packages/flutter/lib/src/scheduler/binding.dart#L218
  - https://github.com/flutter/flutter/pull/89451/files#diff-012f629ab450c5af02ee0de1cf27eb79d5179398858efd0b61f0b66ee3dbd3f0

**Comment by daadu** [comment]
The fix for it has landed on pub.dev with v0.7.3-beta.1.

@mockturtl Thanks for reporting and fixing this bug.

**Comment by daadu** [comment]
v0.7.3-beta.1 promoted to v0.8.0.
