### ISSUE TITLE
Backdrop is not compiling after upgrading to Flutter 3.10

### ISSUE THREAD

**Issue by tobolski** [fluttercommunity/backdrop#127]
**Describe the bug**
After upgrading Flutter to version 3.10.0 I can no longer compile app that is using backdrop package.
This is due to breaking changes in AppBar widget:
https://docs.flutter.dev/release/breaking-changes/3-7-deprecations#appbar-sliverappbar-and-appbartheme-updates

`brightness` and `textTheme` properties have been removed.

**To Reproduce**
1.  Upgrade Flutter to version 3.10.0
2. Try to compile the code.
3. See error:
    app_bar.dart:199:7: Error: No named parameter with the name 'brightness'

**Comment by WieFel** [comment]
@tobolski thank you. will have a look asap

**Comment by daadu** [comment]
@tobolski This has been fixed and released to pub.dev with v0.9.0. 

Thanks for reporting, do check yourself in project's README!
