### ISSUE TITLE
En Flutter 3.10 no compila Por 2 Lineas en el Widget AppBar (brightness y textTheme), las cuales estan en desuso pero el compilador las toma en cuenta, eliminando esas 2 lines el paquete funciona perfectamente

### ISSUE THREAD

**Issue by ZyrusLeo** [fluttercommunity/backdrop#129]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ZyrusLeo** [comment]
Esto es un pequeño aporte para solucionar un paquete que funciona muy bien

**Comment by WieFel** [comment]
gracias @ZyrusLeo!
diplicate of #127

**Comment by daadu** [comment]
Closing this.
