### ISSUE TITLE
ExpansionTile messes up _currentIndex calculations

### ISSUE THREAD

**Issue by skipmeister123** [fluttercommunity/backdrop#13]
**Describe the bug**
I'm trying to convert my old AppBar implementation to the Backdrop implementation.  My menu has ExpansionTiles and ListTiles.  Backdrop doesn't recognize the ListTiles inside my ExpansionTiles, and instead uses the ExpansionTile for the _currentIndex.  This breaks navigation.  To work around this, I set the _currentIndex manually, but the frontLayer doesn't become active after tapping a navigation item.

**To Reproduce**
```dart
backLayer: BackdropNavigationBackLayer(
  items: [
    Container(
      child: new ExpansionTile(
          title: Text("A"),
          children: <Widget>[
            ListTile(
              title: Text("1"),
              onTap: () {
                setState(() => _currentIndex = 0);
              },
            ),
            ListTile(
                title: Text("2"),
                onTap: () {
                  setState(() {
                    _currentIndex = 1;
                  });
                }),
            ListTile(
                title: Text("3"),
                onTap: () {
                  setState(() {
                    _currentIndex = 2;
                  });
                }),
          ]),
    ),
    ListTile(
        title: Text("B"),
        onTap: () {
          setState(() {
            _currentIndex = 5;
          });
        }),
    ListTile(
        title: Text("C"),
        onTap: () {
          setState(() {
            _currentIndex = 6;
          });
        }),
  ],
  onTap: (int position) => {setState(() => _currentIndex = position)},
```
**Expected behavior**
I manually set the _currentIndex, and the frontLayer changes widgets, but does not toggle to active.  I expect it to toggle back to an active state.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/1911919/81478650-bef10f80-91ec-11ea-8795-db1bf06b7070.gif)

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10
 - Browser n/a
 - Version n/a

**Comment by daadu** [comment]
This looks like a custom logic not suitable for `BackdropNavigationBackLayer`. `BackdropNavigationBackLayer` is designed for simple navigation scenario.

Having said that, your code looks almost done, replace `BackdropNavigationBackLayer` with `ListView` or `ListView.builder` and that should do the job. I guess!

**Comment by skipmeister123** [comment]
> PS: You can call `Backdrop.of(context).showFrontLayer()` after `setState()` in `onTap`, to show the front layer

Doesn't appear to be working.

```
ListTile(
  title: Text("Test"),
  onTap: () {
    setState(() => _currentIndex = 0);
    Backdrop.of(context).showFrontLayer();
  },
),
```

```
════════ Exception caught by gesture ═══════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'data' was called on null.
Receiver: null
Tried calling: data

When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      Backdrop.of 
package:backdrop/backdrop.dart:27
#2      _MainPageState.build.<anonymous closure> 
package:t4c_companion/main.dart:129
#3      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:779
#4      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:862
```

**Comment by daadu** [comment]
This error is because of passing wrong `context` to `Backdrop.of`.

You need to put the `backLayer` part in a custom widget or a workaround would be wrap the `ListView` around `LayoutBuilder` and pass the `context` from  `LayoutBuilder` to `Backdrop.of`

**Comment by skipmeister123** [comment]
I ended up with a LayoutBuilder, which did the trick.  Nice catch.  This feels super messy to me, but it works.  Thanks for the assist :)
