### ISSUE TITLE
Pressing Back button cause visible frontLayer

### ISSUE THREAD

**Issue by pishguy** [fluttercommunity/backdrop#132]
I'm not sure why this issue happened but when `frontLayer` isn't visible when i pressing on android back button that cause visible `frontLayer`

my tested code:

```dart
class SplashScreenWidget extends StatefulWidget {
  /// Default constructor for [SplashScreenWidget].
  const SplashScreenWidget({Key? key}) : super(key: key);

  @override
  _SplashScreenWidgetState createState() => _SplashScreenWidgetState();
}

class _SplashScreenWidgetState extends State<SplashScreenWidget> {
  @override
  Widget build(BuildContext context) => MaterialApp(
        title: 'Backdrop Demo',
        home: BackdropScaffold(
          appBar: BackdropAppBar(
            actions: const <Widget>[
              BackdropToggleButton(
                icon: AnimatedIcons.list_view,
              )
            ],
          ),
          backLayer: Center(
            child: Text("Back Layer"),
          ),
          frontLayer: Center(
            child: Text("Front Layer"),
          ),
        ),
      );
}
```

https://github.com/fluttercommunity/backdrop/assets/6617583/cd31983a-7fb4-494e-be3b-33b372474d3b

**Comment by WieFel** [comment]
In my opinion this is the expected behavior.
@daadu what do you think?

**Comment by pishguy** [comment]
@WieFel  You may right, how can i prevent this behavior now?

**Comment by daadu** [comment]
OR

You can file a PR to make this behaviour optional adding option  `bool onBackConcealBacklayer = true` to `BackdropScafold`

**Comment by daadu** [comment]
@WieFel What do you think of this option?

**Comment by WieFel** [comment]
@daadu yeah we can add the option

**Comment by pishguy** [comment]
> Yes, it is expected behaviour.
> 
> The code that does it is at -
> 
> https://github.com/fluttercommunity/backdrop/blob/d21cfaaeae8e3b173fc596f34ac2971897394945/lib/src/scaffold.dart#L617-L619
> 
> Wrapping another `WillPopScope` around `BackdropScaffold`, might not work - because I think flutter will also call the code inside `backdrop` lib. Although you can give it a try.
> 
> As of now, you can fork and remove this widget from the library and use it.

i checked before it doesn't work correctly

**Comment by daadu** [comment]
@WieFel filled PR please review

**Comment by daadu** [comment]
@pishguy Thanks for filling the issue, the `concealBacklayerOnBackButton` option has been added and published to pub.dev with `v0.9.1`. Please check, you can disable this behaviour, by setting it `false`.

Also, check yourself out in the [README.md](https://github.com/fluttercommunity/backdrop#contributors-)!!

**Comment by pishguy** [comment]
i solved closing `frontLayer` when visibility of that is true 

[pull request: 135](https://github.com/fluttercommunity/backdrop/pull/135)
