### ISSUE TITLE
Focus in keyboard

### ISSUE THREAD

**Issue by cicelcup** [fluttercommunity/backdrop#14]
When you are using a front layer that contains one TextField,  if you are typing something on it and then it pressed the leading or action bottom in the backdrop appbar, the keyboard remains open instead of lost the focus. 
(I cannot wrap 

I guess this can be solved adding FocusScope.of(context).unfocus() in the places where fling is called.

(This is the first time in my life that I created some bug report), so please forgive me if I did something wrong.

**Comment by daadu** [comment]
@cicelcup Thank you for reporting the bug. We might take some time to fix it. Meanwhile you can file PR against it if you want. Contributions are welcomed!

**Comment by cicelcup** [comment]
I already do the change. But I am not sure well how to do the pull request. I will mention what I have done so far.. First I clone the project, second, I create another branch, third I did the change, four I commit and then I try to push it but the server rejected... Please can you be kind to tell me how to do the pull request?

**Comment by daadu** [comment]
@cicelcup you need to ["fork" this repo](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) first to your own profile. then clone that repo to your local machine. push the change to your "forked" repo. then create PR from your repo to this one (fluttercommunity/backdrop)

**Comment by cicelcup** [comment]
Thank you for teaching me. I already did what you indicated me.. Regards...

**Comment by daadu** [comment]
@cicelcup Thank you for your contribution at #16. The fix is pushed to pub. Run `flutter pub upgrade`.

Also you have been added as contributor in README.md.

Hope to see more contributions from you.
