### ISSUE TITLE
[Enhancement] Front layer title

### ISSUE THREAD

**Issue by cicelcup** [fluttercommunity/backdrop#24]
Hello. 
I'm not sure if it would be nice to add an optional feature where you can set the title (with basic configuration) of the front layer according to the text provided on the Backdrop navigation layer item?

**Comment by WieFel** [comment]
This will be possible as soon as I merge #23 into master.
I will come back to you with a code snippet ;)

**Comment by cicelcup** [comment]
Thank you very much... If you need any help, just let me know.
