### ISSUE TITLE
After first backdrop toggle: back layer revealed on every front layer click regardless of location

### ISSUE THREAD

**Issue by WieFel** [fluttercommunity/backdrop#39]
**Describe the bug**
In a very simple setting, after having toggled backdrop for the first time (to reveal back layer), the front layer becomes non-responsive and toggles backdrop on every front layer click.

**To Reproduce**
Use this code
```dart
    MaterialApp(
      title: 'Backdrop Demo',
      home: BackdropScaffold(
        appBar: BackdropAppBar(
          title: Text("Backdrop Example"),
          actions: <Widget>[
            BackdropToggleButton(
              icon: AnimatedIcons.list_view,
            )
          ],
        ),
        backLayer: Center(
          child: Text("Back Layer"),
        ),
        subHeader: BackdropSubHeader(
          title: Text("Sub Header"),
        ),
        frontLayer: Center(
          child: MaterialButton(
            child: Text("Click"),
            onPressed: () => print("Clicked!"),
          ),
        ),
      ),
    );
```

1. Click anywhere on front layer (nothing should happen)
2. Toggle backdrop to reveal back layer
3. Toggle backdrop to conceal back layer
4. Click anywhere on front layer (back layer is revealed)
5. Toggle backdrop again to conceal back layer
6. Try to click on front layer button (button cannot be clicked, and backdrop is toggled instead)

**Expected behavior**
Backdrop should not be toggled from front layer if it is revealed.

**Screenshots**
Should be clear enough as is.

**Comment by WieFel** [comment]
This bug is connected to `subHeader`. It only appears when subheader is set...

**Comment by daadu** [comment]
I am not able to reproduce the bug

![untitled](https://user-images.githubusercontent.com/4963236/85952081-9da6d700-b984-11ea-842c-98cc323d08c4.gif)

**Comment by WieFel** [comment]
Ok, let me check on other devices...

**Comment by WieFel** [comment]
The problem is related with the beta channel. On stable channel, I cannot reproduce it either.
I am experiencing the problem while developing the demo app, which needs the beta channel for flutter web support...

**Comment by daadu** [comment]
beta will probably land on stable channel some day. we need to fix this then.

**Comment by WieFel** [comment]
Yes, I'll have a look at it.
