### ISSUE TITLE
Use non-animated Icons with BackdropToggleButton

### ISSUE THREAD

**Issue by heath3n** [fluttercommunity/backdrop#42]
**Request**
I'd like to use icons without being limited to those with current `AnimatedIconData` implementations; `AnimatedIconData` is an abstract class which must be extended to provide drawable path data which seems like overkill.

**What I've tried**
I tried not using `BackdropToggleButton` at all and just using my own button:
```
IconButton(
  icon: Icon(Icons.filter_list),
  onPressed: () => Backdrop.of(context).fling()
)
```
This results in an error (to be honest, I'm not quite sure why):
```
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'data' was called on null.
Receiver: null
Tried calling: data

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Backdrop.of (package:backdrop/scaffold.dart:25:62)
```

**What I'd like**
A constructor such as `BackdropToggleButton({frontIcon, backIcon})`.

My apologies if I'm just doing something wrong here.

**Comment by WieFel** [comment]
You have to wrap your `IconButton` with a `LayoutBuilder` in order to work.
This is needed for `Backdrop.of(context)` to be able to access the `Backdrop` inherited widget.

```dart
  LayoutBuilder(
    builder: (context, constraints) => IconButton(
        icon: Icon(Icons.filter_list),
        onPressed: () => Backdrop.of(context).fling()),
  )
```

**Comment by bielzim0** [comment]
> You have to wrap your `IconButton` with a `LayoutBuilder` in order to work.
> This is needed for `Backdrop.of(context)` to be able to access the `Backdrop` inherited widget.
> 
> ```dart
>   LayoutBuilder(
>     builder: (context, constraints) => IconButton(
>         icon: Icon(Icons.filter_list),
>         onPressed: () => Backdrop.of(context).fling()),
>   )
> ```

This LayoutBuilder should be added to the documentation, it helped me a lot since I wanted to make a different animated icon without the limitations of AnimatedIcons.
