### ISSUE TITLE
problem in scrolling front layer on change of grid delegate

### ISSUE THREAD

**Issue by ankibhandari** [fluttercommunity/backdrop#46]
i want to change the grid delegate in sliver grid on the click of a button from back layer . Grid delegate does change but custom scrollview does not work on the changed grid delegate

**Comment by WieFel** [comment]
@ankibhandari please provide a more detailed description and a simplified code sample of your problem. Else we cannot help you.

**Comment by ankibhandari** [comment]
import 'package:flutter/material.dart';

import 'package:provider/provider.dart';

import 'package:backdrop/backdrop.dart';



import 'package:font_awesome_flutter/font_awesome_flutter.dart';



import 'package:lazy_load_scrollview/lazy_load_scrollview.dart';



import '../providers/categories.dart';

import '../providers/tools.dart';



import '../providers/news.dart';

import '../widgets/news_item.dart';



class CategoryNewsScreen extends StatefulWidget {

  static const routeName = '/category-news';



@override

  _CategoryNewsScreenState createState() => _CategoryNewsScreenState();

}



class _CategoryNewsScreenState extends State<CategoryNewsScreen> {



 var _isInit = true;

 var _loading = false;

  int _numItemsPage = 0;

  var adValue = "desc";

  var newsId;

  bool layout = true;



  @override

  void didChangeDependencies() {

    newsId = ModalRoute.of(context).settings.arguments as int;

    print(newsId);

    print('ankita');

    print(_isInit);

    if (_isInit) {

      print('ankita');

      _numItemsPage = 1;

      apiFetching("YES");







      setState(() {

        _isInit = false;

      });

    }

    super.didChangeDependencies();

  }



  Future<void> _loadMore() async {

    _numItemsPage += 1;

    final categoriesData = Provider.of<Categories>(context, listen: false);



    final noData = categoriesData.noData;

    try {

      if (!noData) {

        apiFetching("NO");



    } catch (error) {

      _dialogBox();

    }





  }



  Future<Null> _refresh() async {



    _numItemsPage = 1;

    _isInit = true;

    apiFetching("YES");

  }



  _dialogBox() {

    showDialog(

        context: context,

        builder: (ctx) => AlertDialog(

                title: Text('An Error occurred'),

                content: Text('Something went wrong'),

                actions: <Widget>[

                  FlatButton(

                    child: Text('Okay'),

                    onPressed: () {

                      Navigator.of(ctx).pop();

                    },

                  )

                ]));

  }





  PopupMenuItem<String> _buildMenuItem(

      IconData icon, String label, String value,

      [bool isSelect = false]) {

    print(value);

    //adValue = value;



    final TextStyle menuItemStyle = TextStyle(

        fontSize: 13.0,

        color: isSelect ? Theme.of(context).primaryColor : Colors.black,

        height: 24.0 / 15.0);

    return PopupMenuItem<String>(

      value: value,

      child: Row(

        children: <Widget>[

          Padding(

            padding: const EdgeInsets.only(right: 24.0),

            child: Icon(icon,

                color: isSelect ? Theme.of(context).primaryColor : Colors
.black,

                size: 17),

          ),

          Text(label, style: menuItemStyle),

        ],

      ),

    );

  }



  void sort(String value) async {

    //final newsId = ModalRoute.of(context).settings.arguments as int;

    print(value);



    adValue = value;

    _numItemsPage = 1;

    _isInit = true;

    apiFetching("YES");

  }



  apiFetching(loadType) {

    if (loadType == "YES") {

      setState(() {

        _loading = true;

      });

    }





    try {

      print('fetching');

      Provider.of<Categories>(context, listen: false)

          .fetchAndSetCatNews(newsId, _isInit, _numItemsPage, adValue)

          .then((_) {

        setState(() {

          _loading = false;

        });

      });

      //print(newsId);

    } catch (error) {

      // print(error);

      _dialogBox();

    }

  }



  @override

  Widget build(BuildContext context) {

    //final newsId = ModalRoute.of(context).settings.arguments as int;

    final loadedProduct =

        Provider.of<Categories>(context, listen: false).findById(newsId);

    final categoriesData = Provider.of<Categories>(context);

    final dNews = categoriesData.dummyNews;

    final noData = categoriesData.noData;



MaterialApp(



         title: 'Backdrop Demo',

        home: BackdropScaffold(

      controller: controller,

      appBar: BackdropAppBar(

        backgroundColor: Theme.of(context).primaryColor,

        leading: IconButton(

          icon: Icon(Icons.arrow_back),

          onPressed: () => Navigator.of(context).pop(),

        ),

        title: Text(_title[_currentIndex], style: TextStyle(fontSize: 15)),

        actions: <Widget>[

          PopupMenuButton<String>(

            icon: Icon(FontAwesomeIcons.sort, color: Colors.white, size:
18),

            onSelected: sort,

            itemBuilder: (BuildContext context) => <PopupMenuItem<String>>[

              _buildMenuItem(FontAwesomeIcons.sortNumericUp, 'Date ASC',
"asc",

                  adValue == "asc"),

              _buildMenuItem(FontAwesomeIcons.sortNumericDown, 'Date DESC',

                  "desc", adValue == "desc"),

            ],

          ),

          BackdropToggleButton(

            icon: AnimatedIcons.close_menu,

          )

        ],

      ),

      stickyFrontLayer: true,

frontLayer:_loading ? Center(

                    child: CircularProgressIndicator(),

                  )

                : LazyLoadScrollView(

                    onEndOfPage: _loadMore,

                    child: RefreshIndicator(

                      onRefresh: _refresh,

                      child: CustomScrollView(



                        slivers: <Widget>[

                          SliverPadding(

                            padding: EdgeInsets.all(10),

                            sliver: SliverGrid(

                              delegate: SliverChildBuilderDelegate(

                                (c, index) =>

                                    //

                                    NewsItem(

                                  id: dNews[index].id,

                                  title: dNews[index].title,

                                  imageUrl: dNews[index].imageUrl,

                                  date: dNews[index].date,

                                ),

                                childCount: dNews.length,

                              ),

                              //itemCount: dNews.length,

                              gridDelegate: layout

                                  ?
SliverGridDelegateWithFixedCrossAxisCount(

                                      crossAxisCount: 2,

                                      childAspectRatio: 1.2,

                                      crossAxisSpacing: 10,

                                      mainAxisSpacing: 5)

                                  :
SliverGridDelegateWithFixedCrossAxisCount(

                                      crossAxisCount: 1,

                                      childAspectRatio: 1.5,

                                      crossAxisSpacing: 10,

                                      mainAxisSpacing: 0),

                              //padding: const EdgeInsets.all(10),

                            ),

                          ),

                          SliverToBoxAdapter(

                            child: noData == false

                                ? Center(child: CircularProgressIndicator())

                                : Container(),

                          ),

                        ],

                      ),

                    )



backLayer: BackdropNavigationBackLayer(

          //separator: Text('Filters'),

          items: [

            Column(

              crossAxisAlignment: CrossAxisAlignment.start,

              children: <Widget>[

                SizedBox(

                  height: 20,

                ),

                Padding(

                  padding: EdgeInsets.only(left: 20),

                  child: Text(

                    "Layouts",

                    style: TextStyle(

                      fontSize: 21,

                      fontWeight: FontWeight.w500,

                      color: Colors.white,

                    ),

                  ),

                ),

                SizedBox(

                  height: 10.0,

                ),

                ListTile(

                  title: Icon(Icons.grid_on),

                ),

                ListTile(title: Text("Widget 2")),

              ],

            ),

          ], onTap: (int position) => {setState(() => layout = false)}),

    ));

**Comment by ankibhandari** [comment]
this change properly works without backdrop package but with backdrop scroll doesn't work after the change of layout

**Comment by WieFel** [comment]
@ankibhandari sorry to be so fussy but would you mind posting the code again (or editing your comment) using the ``` tags in order to format it as code and removing the empty lines? This would make it more easily readable...

**Comment by ankibhandari** [comment]
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:backdrop/backdrop.dart';

import 'package:font_awesome_flutter/font_awesome_flutter.dart';

import 'package:lazy_load_scrollview/lazy_load_scrollview.dart';

import '../providers/categories.dart';
import '../providers/tools.dart';

import '../providers/news.dart';
import '../widgets/news_item.dart';

class CategoryNewsScreen extends StatefulWidget {
  static const routeName = '/category-news';
  
  @override
  _CategoryNewsScreenState createState() => _CategoryNewsScreenState();
}

class _CategoryNewsScreenState extends State<CategoryNewsScreen> {

  var _isInit = true;
  int _currentIndex = 0;

  var _loading = false;
  int _numItemsPage = 0;
  var adValue = "desc";
  var newsId;
  bool layout = true;
  var changeIcon = Icon(Icons.menu);
  @override
  void didChangeDependencies() {
    newsId = ModalRoute.of(context).settings.arguments as int;
   if (_isInit) {
   
      _numItemsPage = 1;
      apiFetching("YES");
      
      setState(() {
        _isInit = false;
      });
    }
    super.didChangeDependencies();
  }

  Future<void> _loadMore() async {
   _numItemsPage += 1;
    final categoriesData = Provider.of<Categories>(context, listen: false);

    final noData = categoriesData.noData;
    try {
      if (!noData) {
        apiFetching("NO");
      }
    } catch (error) {
      _dialogBox();
    }
 }

  Future<Null> _refresh() async {
    _numItemsPage = 1;
    _isInit = true;
    apiFetching("YES");
  }

  _dialogBox() {
    showDialog(
        context: context,
        builder: (ctx) => AlertDialog(
                title: Text('An Error occurred'),
                content: Text('Something went wrong'),
                actions: <Widget>[
                  FlatButton(
                    child: Text('Okay'),
                    onPressed: () {
                      Navigator.of(ctx).pop();
                    },
                  )
                ]));
  }

  PopupMenuItem<String> _buildMenuItem(
      IconData icon, String label, String value,
      [bool isSelect = false]) {
    print(value);
   
    final TextStyle menuItemStyle = TextStyle(
        fontSize: 13.0,
        color: isSelect ? Theme.of(context).primaryColor : Colors.black,
        height: 24.0 / 15.0);
    return PopupMenuItem<String>(
      value: value,
      child: Row(
        children: <Widget>[
          Padding(
            padding: const EdgeInsets.only(right: 24.0),
            child: Icon(icon,
                color: isSelect ? Theme.of(context).primaryColor : Colors.black,
                size: 17),
          ),
          Text(label, style: menuItemStyle),
        ],
      ),
    );
  }

  void sort(String value) async {
    adValue = value;
    _numItemsPage = 1;
    _isInit = true;
    apiFetching("YES");
  }

  apiFetching(loadType) {
    if (loadType == "YES") {
      setState(() {
        _loading = true;
      });
    }

    try {
      print('fetching');
      Provider.of<Categories>(context, listen: false)
          .fetchAndSetCatNews(newsId, _isInit, _numItemsPage, adValue)
          .then((_) {
        setState(() {
          _loading = false;
        });
      });
     
    } catch (error) {
      _dialogBox();
    }
  }

  @override
  Widget build(BuildContext context) {
    final loadedProduct =
        Provider.of<Categories>(context, listen: false).findById(newsId);
    final categoriesData = Provider.of<Categories>(context);
    final dNews = categoriesData.dummyNews;
    final noData = categoriesData.noData;

   MaterialApp(

        title: 'Backdrop Demo',
        home: BackdropScaffold(
      controller: controller,
      appBar: BackdropAppBar(
        backgroundColor: Theme.of(context).primaryColor,
        leading: IconButton(
          icon: Icon(Icons.arrow_back),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(_title[_currentIndex], style: TextStyle(fontSize: 15)),
        actions: <Widget>[
          PopupMenuButton<String>(
            icon: Icon(FontAwesomeIcons.sort, color: Colors.white, size: 18),
            onSelected: sort,
            itemBuilder: (BuildContext context) => <PopupMenuItem<String>>[
              _buildMenuItem(FontAwesomeIcons.sortNumericUp, 'Date ASC', "asc",
                  adValue == "asc"),
              _buildMenuItem(FontAwesomeIcons.sortNumericDown, 'Date DESC',
                  "desc", adValue == "desc"),
            ],
          ),
          BackdropToggleButton(
            icon: AnimatedIcons.close_menu,
          )
        ],
      ),
      stickyFrontLayer: true, 
        frontLayer: _loading
                ? Center(
                    child: CircularProgressIndicator(),
                  )
                : LazyLoadScrollView(
                    onEndOfPage: _loadMore,
                    child: RefreshIndicator(
                      onRefresh: _refresh,
                      child: CustomScrollView(
                        slivers: <Widget>[
                          SliverPadding(
                            padding: EdgeInsets.all(10),
                            sliver: SliverGrid(
                              delegate: SliverChildBuilderDelegate(
                                (c, index) =>
                                    
                                    NewsItem(
                                  id: dNews[index].id,
                                  title: dNews[index].title,
                                  imageUrl: dNews[index].imageUrl,
                                  date: dNews[index].date,
                                ),
                                childCount: dNews.length,
                              ),
                              
                              gridDelegate: layout
                                  ? SliverGridDelegateWithFixedCrossAxisCount(
                                      crossAxisCount: 2,
                                      childAspectRatio: 1.2,
                                      crossAxisSpacing: 10,
                                      mainAxisSpacing: 5)
                                  : SliverGridDelegateWithFixedCrossAxisCount(
                                      crossAxisCount: 1,
                                      childAspectRatio: 1.5,
                                      crossAxisSpacing: 10,
                                      mainAxisSpacing: 0),
                        
                            ),
                          ),
                          SliverToBoxAdapter(
                            child: noData == false
                                ? Center(child: CircularProgressIndicator())
                                : Container(),
                          ),
                        ],
                      ),
                    )
                    ));
    backLayer: BackdropNavigationBackLayer(
          
          items: [
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                SizedBox(
                  height: 20,
                ),
                Padding(
                  padding: EdgeInsets.only(left: 20),
                  child: Text(
                    "Layouts",
                    style: TextStyle(
                      fontSize: 21,
                      fontWeight: FontWeight.w500,
                      color: Colors.white,
                    ),
                  ),
                ),
                SizedBox(
                  height: 10.0,
                ),
                ListTile(
                  title: Icon(Icons.grid_on),
                ),
                ListTile(title: Text("Widget 2")),
              ],
            ),
          ], onTap: (int position) => {setState(() => layout = false)}),
    )); 
  }
}

**Comment by ankibhandari** [comment]
please inform me if you require anything else

**Comment by WieFel** [comment]
@ankibhandari thank you, I will have a look

**Comment by WieFel** [comment]
@ankibhandari if you replace `BackdropScaffold` with a normal material `Scaffold`, are you facing the same problem?

**Comment by ankibhandari** [comment]
No ,i am not facing any problem with normal material Scaffold. It is working correctly. I am attaching the code below which is working correctly.


return
        Scaffold(
            appBar: AppBar(
                title: Text(loadedProduct.name, style: TextStyle(fontSize: 15)),
                actions: <Widget>[
                  PopupMenuButton<String>(
                    icon: Icon(FontAwesomeIcons.sort,
                        color: Colors.white, size: 18),
                    onSelected: sort,
                    itemBuilder: (BuildContext context) =>
                        <PopupMenuItem<String>>[
                      _buildMenuItem(FontAwesomeIcons.sortNumericUp, 'Date ASC',
                          "asc", adValue == "asc"),
                      _buildMenuItem(FontAwesomeIcons.sortNumericDown,
                          'Date DESC', "desc", adValue == "desc"),
                    ],
                  ),
                  IconButton(
                      icon:
                          layout ? Icon(Icons.menu) : Icon(Icons.view_compact),
                      onPressed: () => {
                           
                            setState(() => layout = !layout),
                          })
                ]),
            body: _loading
                ? Center(
                    child: CircularProgressIndicator(),
                  )
                : LazyLoadScrollView(
                    onEndOfPage: _loadMore,
                    child: RefreshIndicator(
                      onRefresh: _refresh,
                      child: CustomScrollView(
                        slivers: <Widget>[
                          SliverPadding(
                            padding: EdgeInsets.all(10),
                            sliver: SliverGrid(
                              delegate: SliverChildBuilderDelegate(
                                (c, index) =>
                                   NewsItem(
                                  id: dNews[index].id,
                                  title: dNews[index].title,
                                  imageUrl: dNews[index].imageUrl,
                                  date: dNews[index].date,
                                ),
                                childCount: dNews.length,
                              ),
                            
                              gridDelegate: layout
                                  ? SliverGridDelegateWithFixedCrossAxisCount(
                                      crossAxisCount: 2,
                                      childAspectRatio: 1.2,
                                      crossAxisSpacing: 10,
                                      mainAxisSpacing: 5)
                                  : SliverGridDelegateWithFixedCrossAxisCount(
                                      crossAxisCount: 1,
                                      childAspectRatio: 1.5,
                                      crossAxisSpacing: 10,
                                      mainAxisSpacing: 0),
                            
                            ),
                          ),
                          SliverToBoxAdapter(
                            child: noData == false
                                ? Center(child: CircularProgressIndicator())
                                : Container(),
                          ),
                        ],
                      ),
                    )
                    ));
  }
}

**Comment by ankibhandari** [comment]
No ,i am not facing any problem with normal material Scaffold. It is working correctly. I am attaching the code below which is working correctly.

@override
  Widget build(BuildContext context) {
   
    final loadedProduct =
        Provider.of<Categories>(context, listen: false).findById(newsId);
    final categoriesData = Provider.of<Categories>(context);
    final dNews = categoriesData.dummyNews;
    final noData = categoriesData.noData;

return
        Scaffold(
           appBar: AppBar(
                title: Text(loadedProduct.name, style: TextStyle(fontSize: 15)),
                  actions: [
PopupMenuButton(
icon: Icon(FontAwesomeIcons.sort,
color: Colors.white, size: 18),
onSelected: sort,
itemBuilder: (BuildContext context) =>
<PopupMenuItem>[
_buildMenuItem(FontAwesomeIcons.sortNumericUp, 'Date ASC',
"asc", adValue == "asc"),
_buildMenuItem(FontAwesomeIcons.sortNumericDown,
'Date DESC', "desc", adValue == "desc"),
],
),
IconButton(
icon:
layout ? Icon(Icons.menu) : Icon(Icons.view_compact),
onPressed: () => {

                        setState(() => layout = !layout),
                      })
            ]),
        body: _loading
            ? Center(
                child: CircularProgressIndicator(),
              )
            : LazyLoadScrollView(
                onEndOfPage: _loadMore,
                child: RefreshIndicator(
                  onRefresh: _refresh,
                  child: CustomScrollView(
                    slivers: <Widget>[
                      SliverPadding(
                        padding: EdgeInsets.all(10),
                        sliver: SliverGrid(
                          delegate: SliverChildBuilderDelegate(
                            (c, index) =>
                               NewsItem(
                              id: dNews[index].id,
                              title: dNews[index].title,
                              imageUrl: dNews[index].imageUrl,
                              date: dNews[index].date,
                            ),
                            childCount: dNews.length,
                          ),
                        
                          gridDelegate: layout
                              ? SliverGridDelegateWithFixedCrossAxisCount(
                                  crossAxisCount: 2,
                                  childAspectRatio: 1.2,
                                  crossAxisSpacing: 10,
                                  mainAxisSpacing: 5)
                              : SliverGridDelegateWithFixedCrossAxisCount(
                                  crossAxisCount: 1,
                                  childAspectRatio: 1.5,
                                  crossAxisSpacing: 10,
                                  mainAxisSpacing: 0),
                        
                        ),
                      ),
                      SliverToBoxAdapter(
                        child: noData == false
                            ? Center(child: CircularProgressIndicator())
                            : Container(),
                      ),
                    ],
                  ),
                )
                ));
}
}

**Comment by ankibhandari** [comment]
@override
  Widget build(BuildContext context) {

    final loadedProduct =
        Provider.of<Categories>(context, listen: false).findById(newsId);
    final categoriesData = Provider.of<Categories>(context);
    final dNews = categoriesData.dummyNews;
    final noData = categoriesData.noData;
    return Scaffold(
           
            appBar: AppBar(
                title: Text(loadedProduct.name, style: TextStyle(fontSize: 15)),
                actions: <Widget>[
                  PopupMenuButton<String>(
                    icon: Icon(FontAwesomeIcons.sort,
                        color: Colors.white, size: 18),
                    onSelected: sort,
                    itemBuilder: (BuildContext context) =>
                        <PopupMenuItem<String>>[
                      _buildMenuItem(FontAwesomeIcons.sortNumericUp, 'Date ASC',
                          "asc", adValue == "asc"),
                      _buildMenuItem(FontAwesomeIcons.sortNumericDown,
                          'Date DESC', "desc", adValue == "desc"),
                    ],
                  ),
                  IconButton(
                      icon:
                          layout ? Icon(Icons.menu) : Icon(Icons.view_compact),
                      onPressed: () => {
                            setState(() => layout = !layout),
                          })
                ]),
            body: _loading
                ? Center(
                    child: CircularProgressIndicator(),
                  )
                : LazyLoadScrollView(
                    onEndOfPage: _loadMore,
                    child: RefreshIndicator(
                      onRefresh: _refresh,
                      child: CustomScrollView(
                        slivers: <Widget>[
                          SliverPadding(
                            padding: EdgeInsets.all(10),
                            sliver: SliverGrid(
                              delegate: SliverChildBuilderDelegate(
                                (c, index) => NewsItem(
                                  id: dNews[index].id,
                                  title: dNews[index].title,
                                  imageUrl: dNews[index].imageUrl,
                                  date: dNews[index].date,
                                ),
                                childCount: dNews.length,
                              ),
                              gridDelegate: layout
                                  ? SliverGridDelegateWithFixedCrossAxisCount(
                                      crossAxisCount: 2,
                                      childAspectRatio: 1.2,
                                      crossAxisSpacing: 10,
                                      mainAxisSpacing: 5)
                                  : SliverGridDelegateWithFixedCrossAxisCount(
                                      crossAxisCount: 1,
                                      childAspectRatio: 1.5,
                                      crossAxisSpacing: 10,
                                      mainAxisSpacing: 0),
                            ),
                          ),
                          SliverToBoxAdapter(
                            child: noData == false
                                ? Center(child: CircularProgressIndicator())
                                : Container(),
                          ),
                        ],
                      ),
                    )
                    ));
  }
}

**Comment by ankibhandari** [comment]
No ,i am not facing any problem with normal material Scaffold. It is working correctly. I have sent you the code above which is working correctly.

**Comment by WieFel** [comment]
I am not able to run your code as it contains some custom classes/providers. I think your problem might be related with the state not updating correctly after the button click.
I suggest you to try some more debugging @ankibhandari.

**Comment by daadu** [comment]
@ankibhandari Please provide smallest possible code snippet that can reproduce the error/bug.

Closing this issue till then.
