### ISSUE TITLE
color BackdropToggleButton

### ISSUE THREAD

**Issue by iLDA1997** [fluttercommunity/backdrop#48]
how can i change color of BackdropToggleButton?

**Comment by daadu** [comment]
Create any button you want and in `onPress` add `Backdrop.of(context).fling()` to it

**Comment by iLDA1997** [comment]
i need this icon with black color

BackdropToggleButton(
icon: AnimatedIcons.home_menu,),

**Comment by iLDA1997** [comment]
> Create any button you want and in `onPress` add `Backdrop.of(context).fling()` to it

i need this icon with black color

BackdropToggleButton(
icon: AnimatedIcons.home_menu,),

**Comment by WieFel** [comment]
You can take the code of [BackdropToggleButton](https://github.com/fluttercommunity/backdrop/blob/master/lib/button.dart) and adapt it to add the color property like so:
```dart
        appBar: BackdropAppBar(
          ...
          leading: LayoutBuilder(
            builder: (context, constraints) => IconButton(
              icon: AnimatedIcon(
                icon: AnimatedIcons.close_menu,
                color: Colors.white,
                progress: Backdrop.of(context).controller.view,
              ),
              onPressed: () => Backdrop.of(context).fling(),
            ),
          ),
        )
```

`LayoutBuilder` is necessary to make `Backdrop` accessible as it is an `InheritedWidget`. @iLDA1997 hope this helps.

@daadu maybe we should expose the `AnimatedIcon`'s `color` property of `BackdropToggleButton` in a future release. I myself have already done that in my fork ;)

**Comment by daadu** [comment]
@WieFel Sure, Let's do it then.

**Comment by iLDA1997** [comment]
@WieFel @daadu 

Thanks

**Comment by WieFel** [comment]
@daadu just pushed this small change directly to master.

@iLDA1997 if you want you could meanwhile use the backdrop master branch as dependency and change the color like so:
```dart
        appBar: BackdropAppBar(
          ...
          leading: BackdropToggleButton(
            color: Colors.white,
          ),
        )
```

Or simply wait for the next relase ;)

**Comment by daadu** [comment]
This feature has landed in [`v0.4.4` on pub.dev](https://pub.dev/packages/backdrop/versions/0.4.4)

**Comment by daadu** [comment]
@PembaTamang  Check yourself on repo and pub README for your contribution!!

**Comment by daadu** [comment]
@iLDA1997  Check yourself on repo and pub README for your contribution!!
