### ISSUE TITLE
Cannot set inactiveOverlayColor to transparent

### ISSUE THREAD

**Issue by PembaTamang** [fluttercommunity/backdrop#49]
The inactiveOverLayColor set to Colors.transparent does not work

My layout

```
BackdropScaffold(
      appBar: BackdropAppBar(
        backgroundColor: Colors.deepOrange,
        title: Text('Food Delivery App'),
      ),
      backLayer:  Container(
        height: 200.0,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Padding(
              padding: const EdgeInsets.only(left: 16,top: 16),
              child: Text('Theme',style: TextStyle(color: Colors.white,fontWeight: FontWeight.bold),),
            ),
        SwitchListTile(
          activeColor: Colors.orange,
        inactiveThumbColor: Colors.black,
        title: Text('$themeText',style: TextStyle(color: Colors.white,fontWeight: FontWeight.w400)),
        value: _lights,
        onChanged: (bool value) { setState(() {
          _lights = value;
          themeText = value? 'Light':'Dark';
        }); },
        secondary: const Icon(Icons.lightbulb_outline,color: Colors.white,),
      ),
          ],
        ),
      ),
      frontLayer: Center(
        child: SafeArea(
          child: Container(
            decoration: BoxDecoration(
                gradient: LinearGradient(colors: [
                  Colors.orange,
                  Colors.deepOrange.withOpacity(0.9),
                  Colors.deepOrange,
                ], begin: Alignment.bottomCenter, end: Alignment.topCenter)),
            child: ListView(
              padding: EdgeInsets.symmetric(horizontal: 8.0),
              children: [
                SizedBox(height: 10),
                TopInfo(),
                FoodCategory(),
                SizedBox(height: 10),
                SearchField(),
                SizedBox(height: 10),
                MiddleLayout(),
                Column(
                  children: foods.map((FoodData food) {
                    return getFoodItems(food);
                  }).toList(),
                ),

              ],
            ),
          ),

        ),
      ),
      stickyFrontLayer: true,
      resizeToAvoidBottomInset: false,
      backLayerBackgroundColor: Colors.deepOrange,
      animationCurve: Curves.easeIn,
      inactiveOverlayColor: Colors.transparent,
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          print('pressed');
        },
        child: Icon(
          Icons.category,
          color: Colors.black45,
        ),
        backgroundColor: Colors.orangeAccent,
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,

    );
```

I have also tried to set a color withAlpa(0) that is not working as well
Also there is no option to add a bottomnav or a bottomappbar in BackdropScaffold
like the regular scaffold. 
![WhatsApp Image 2020-09-05 at 21 14 19](https://user-images.githubusercontent.com/32651212/92308666-ebf7d800-efbc-11ea-8353-b137ccf09598.jpeg)

**Comment by daadu** [comment]
@WieFel The suggestion for adding `bottomNavigation` and `bottomAppBar` to `BackdropScaffold` like `Scaffold`, is good one. What do you think? And also can you please look into this issue?

**Comment by WieFel** [comment]
@PembaTamang newest commit on master now offers the `bottomNavigationBar` to be set on `BackdropScaffold`. Please use the master branch as dependency until the next release is published on dart pub!

Regarding the issue with the transparent inactive color: The problem is that the `inactiveOverlayColor` is applied a `.withOpacity(0.7)` as defined by the material design guidelines. https://github.com/fluttercommunity/backdrop/blob/993c2959c49353347c6caa711ca41cd5b03e479e/lib/scaffold.dart#L413-L416
However, we could offer a way to pass a completely customized inactive layer to `BackdropScaffold`. If set, the custom inactive layer is used. Else the default inactive layer is applied. @daadu what do you think?

**Comment by PembaTamang** [comment]
sure I'll use the master branch and it seems like a good idea to let a customized inactive layer. That's what I tried soon as I setup this library. I guess it is necessary. Thanks for the response guys

**Comment by PembaTamang** [comment]
hey guys the bottomnavbar is working but the BackdropScaffold is still missing a thing.
When I add a fab to the bnb and make a notch the back of the notch is not transparent. The normal scaffold has an attribure `extendBody: true` that makes the notch bg transparent.
Please add that. Refer to [this](https://stackoverflow.com/questions/59455684/how-to-make-bottomnavigationbar-notch-transparent) post.

**Comment by WieFel** [comment]
Done! Please use the latest commit on master @PembaTamang.

@daadu we should think of exposing **all** of the remaining properties of `Scaffold` so that `BackdropScaffold` can be used just like a normal scaffold, but adds the additional functionality to it.

**Comment by daadu** [comment]
@WieFel I agree about adding all possible configurations of `Scaffold`, and about `inactiveOverlayColor`, transparency is essential, to make the content of `frontLayer` visible. I would suggest adding another attribute `inactiveOverlayOpacity` which defaults to `0.7` and is applied on `inactiveOverlayColor`. 

For transparent overlay, user has to set `inactiveOverlayOpacity` to `0`, i guess that should work, or we can provide a bool flag (say `showInactiveOverlay`, defaults to `true`) to disable overlayColor.

What do you think @WieFel ?

**Comment by WieFel** [comment]
> @WieFel I agree about adding all possible configurations of `Scaffold`, and about `inactiveOverlayColor`, transparency is essential, to make the content of `frontLayer` visible. I would suggest adding another attribute `inactiveOverlayOpacity` which defaults to `0.7` and is applied on `inactiveOverlayColor`.

Yeah that's a good idea! I think a property `inactiveOverlayOpacity` works well. Will implement this in a feature branch tomorrow.

**Comment by PembaTamang** [comment]
yes making it an enchanced Scaffold with all the properties is the way to go. Eagerly waiting to use this.

**Comment by PembaTamang** [comment]
is it ready guys??

**Comment by WieFel** [comment]
Waiting for @daadu's review on the pull request... Going to be ready very soon.

**Comment by daadu** [comment]
This feature has landed in [`v0.4.4` on pub.dev](https://pub.dev/packages/backdrop/versions/0.4.4)

**Comment by PembaTamang** [comment]
thanks a ton!!!  @daadu @WieFel

**Comment by daadu** [comment]
@PembaTamang  Check yourself on repo and pub README for your contribution!!

**Comment by PembaTamang** [comment]
@daadu wow thanks!!
