### ISSUE TITLE
Show front layer using another widget. reveal the front layer on tap of a button.

### ISSUE THREAD

**Issue by PembaTamang** [fluttercommunity/backdrop#50]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by WieFel** [comment]
This is easily possible:
```dart
      BackdropScaffold(
        appBar: BackdropAppBar(
          title: Text("Backdrop Example"),
          automaticallyImplyLeading: false,
        ),
        backLayer: Center(
          child: Text("Back Layer"),
        ),
        subHeader: BackdropSubHeader(
          title: Text("Sub Header"),
        ),
        frontLayer: Center(
          child: LayoutBuilder(
            builder: (context, constraints) => RaisedButton(
              child: Text("Trigger Backdrop"),
              onPressed: () {
                Backdrop.of(context).fling();
              },
            ),
          ),
        ),
      )
```

Use `Backdrop.of(context).fling();` from anywhere in the widget tree below `BackdropScaffold` to trigger the backdrop functionality. For more information check out [the backdrop demo project](https://github.com/fluttercommunity/backdrop/tree/master/demo).

**Comment by PembaTamang** [comment]
oh yeah , didn't see that. I was just too excited to use this.
