### ISSUE TITLE
[bug?] Revealed back layout in post frame callback is not concealed

### ISSUE THREAD

**Issue by proninyaroslav** [fluttercommunity/backdrop#54]
Hi. I was trying to simulate the automatic revealing of the back layer right after the widget tree was created. For this, I placed a `BackdropScaffoldState::revealBackLayer()` call in `WidgetsBinding.instance.addPostFrameCallback()`. It works, but there is a side effect: when I tap the "Close" button to conceal the back layer, it doesn't concealed, it just doesn't respond when clicked. I gave an example here to make it easier to understand what it is about.

```Dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Backdrop Example',
      theme: ThemeData(
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: BackdropScaffold(
        appBar: BackdropAppBar(
          title: Text("Backdrop Example"),
        ),
        backLayer: BackLayer(
          text: "Back Layer",
        ),
        frontLayer: Center(
          child: Text("Front Layer"),
        ),
      ),
    );
  }
}

class BackLayer extends StatelessWidget {
  final String text;

  BackLayer({Key key, this.text}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      Backdrop.of(context).revealBackLayer();
    });

    return Container(
      child: Center(child: Text(text)),
    );
  }
}
```

**Comment by WieFel** [comment]
@proninyaroslav the problem is you are calling
```dart
    WidgetsBinding.instance.addPostFrameCallback((_) {
      Backdrop.of(context).revealBackLayer();
    });
```
every time the build method is executed. So back layer always gets revealed when the UI is repainted.

Convert the `BackLayer` to a `StatefulWidget` and put the code within `initState()` instead of `build()`. This way, the code is executed only after the very first paint.

**Comment by proninyaroslav** [comment]
Thank you.
