### ISSUE TITLE
fontLayer background Color

### ISSUE THREAD

**Issue by lt94** [fluttercommunity/backdrop#60]
i use this code
```dart
frontLayer: Container(
   decoration: BoxDecoration(
                color: Colors.red
)
```
or 
```dart
frontLayer: Containe(
    color:Colors.red
)
```
but,the container color  didn't change. is there any wrong with my code?

**Comment by WieFel** [comment]
Try to give it some `height` and `width` or give it a `child`. Does that help?

**Comment by lt94** [comment]
> Try to give it some `height` and `width` or give it a `child`. Does that help?

thx! it solved my problem~~
