### ISSUE TITLE
Spin-off "demo" app components as separate package.

### ISSUE THREAD

**Issue by daadu** [fluttercommunity/backdrop#62]
Time to spin-off the components of demo app that could be reused by other package maintainer to build similar "demo" app. 

Here are some pointers/questions about it:

- What should we call it? - `demo_maker`, `demoize`, `gallerize`, or something else (suggest in comment)
- @WieFel I suggest you be the primary maintainer of the project and repo.
- Some feature still needs to be implemented to make it like gallery app - having toggle for fullscreen/mobile view. Although this is non-blocking, could be implemented in future.
- The proposed package should also be submitted to fluttercommunity org.
- backdrop - should use the planned package for it's demo app.

This issue will only be open until separate repo for it is created.

**Comment by daadu** [comment]
@WieFel Go ahead with it man!

**Comment by WieFel** [comment]
@daadu will think about it and come back to it!

**Comment by daadu** [comment]
Issue further discussed at https://github.com/WieFel/gallerize/issues/1

**Comment by WieFel** [comment]
@daadu I will adapt demo app to use https://github.com/WieFel/gallerize asap.
