### ISSUE TITLE
swipe body to close

### ISSUE THREAD

**Issue by farokhze** [fluttercommunity/backdrop#68]
Hello,
How can i close backdrop by swipe to top?

**Comment by WieFel** [comment]
Hi @farokhze, this package doesn't support swipe gestures out of the box as it is not recommended according to [material design guidelines](https://material.io/components/backdrop#behavior):
![dont](https://user-images.githubusercontent.com/8345062/99284357-728b2a00-2836-11eb-99cc-361604065231.png)

If you still need to do it, I suggest you try with using `GestureDetector`, maybe by wrapping your `frontLayer` with it (I haven't tried if it works...)

**Comment by daadu** [comment]
Closing this issue, since out of scope of this package.

However, as @WieFel suggested you can do it wrapping your `frontLayer` with `GestureDetector` and calling `Backdrop.of(context).concealBackLayer` (make sure the `context` passed is of the widget below `BackdropScaffold`). Something like the following:

```dart
BackdropScaffold(
  ...
  frontLayer: LayoutBuilder(
    builder: (context, _) => GestureDetector(
      onPressed: (){
        BackdropScaffold.of(context).concealBackLayer();
      },
      child: ...
    ),
  ),
)
```

**Comment by yagizdo** [comment]
> Closing this issue, since out of scope of this package.
> 
> However, as @WieFel suggested you can do it wrapping your `frontLayer` with `GestureDetector` and calling `Backdrop.of(context).concealBackLayer` (make sure the `context` passed is of the widget below `BackdropScaffold`). Something like the following:
> 
> ```dart
> BackdropScaffold(
>   ...
>   frontLayer: LayoutBuilder(
>     builder: (context, _) => GestureDetector(
>       onPressed: (){
>         BackdropScaffold.of(context).concealBackLayer();
>       },
>       child: ...
>     ),
>   ),
> )
> ```

BackdropScaffold.of method is not working now. 

It says .of is not defined.

**Comment by daadu** [comment]
@yagizdo It is `Backdrop.of(context)` not `BackdropScaffold.of`

**Comment by yagizdo** [comment]
Oh okey. Seeing it like that in the example, I tried it. The example is old then.

**Comment by WieFel** [comment]
> Oh okey. Seeing it like that in the example, I tried it. The example is old then.

Which example exactly?

**Comment by yagizdo** [comment]
This

> Closing this issue, since out of scope of this package.
> 
> However, as @WieFel suggested you can do it wrapping your `frontLayer` with `GestureDetector` and calling `Backdrop.of(context).concealBackLayer` (make sure the `context` passed is of the widget below `BackdropScaffold`). Something like the following:
> 
> ```dart
> BackdropScaffold(
>   ...
>   frontLayer: LayoutBuilder(
>     builder: (context, _) => GestureDetector(
>       onPressed: (){
>         BackdropScaffold.of(context).concealBackLayer();
>       },
>       child: ...
>     ),
>   ),
> )
> ```

**Comment by daadu** [comment]
Oops! correcting it.
