### ISSUE TITLE
[CI/CD] for demo deployment is failing

### ISSUE THREAD

**Issue by daadu** [fluttercommunity/backdrop#79]
**Failed Runs**
- https://github.com/fluttercommunity/backdrop/actions/runs/591532419 for v0.5.0 tag
- https://github.com/fluttercommunity/backdrop/actions/runs/591545316 for v0.5.1 tag

**Comment by daadu** [comment]
@WieFel Can you look into it.

**Comment by WieFel** [comment]
Solved!
