### ISSUE TITLE
Set fullscreen back layer

### ISSUE THREAD

**Issue by TenPetr** [fluttercommunity/backdrop#81]
Hello,

I would like to set the back layer fullscreen. Currently, there is this inactive part at the bottom, and I would like to basically push back layer over whole screen. Do you think, that is possible somehow in the current version?

Thanks a lot!

**Comment by WieFel** [comment]
@TenPetr you can try if setting `headerHeight: 0` solves the problem.

Else I would have to check later...

**Comment by TenPetr** [comment]
Worked for me! Thanks a lot!
