### ISSUE TITLE
Padding missing for the action items in the BackdropAppBar.

### ISSUE THREAD

**Issue by AjayrajSingh** [fluttercommunity/backdrop#90]
While adding widgets like Circle Avatar or any custom widget there is no default padding on the BackdropAppBar. Icon Buttons comes with default padding and hence there is no need to add so, but it is not the case for other widgets.
```
appBar: BackdropAppBar(
        title: Text("Beacon"),
        centerTitle: true,
        actions: [
          CircleAvatar(), //This widget is placed to the very right side of the screen
        ],
      ),
```
The app bar should come with fixed padding. For fixing the extra space when adding IconButton we can define the theme property for IconButton and make the padding zero.

**Comment by WieFel** [comment]
`BackdropAppBar` internally is just a normal material `AppBar`. So it doesn't differ in padding...
You can see a comparison here:
1. Using `BackdropAppBar`:
```dart
BackdropAppBar(
  title: Text("Backdrop Example"),
  actions: <Widget>[
    CircleAvatar(),
  ],
)
```
<img width="25%" src="https://user-images.githubusercontent.com/8345062/114079378-6cabe900-98aa-11eb-8218-d014c348bb39.png" alt="screenshot-1"></img>
2. Using normal material `AppBar`:
```dart
AppBar(
  title: Text("Backdrop Example"),
  actions: <Widget>[
    CircleAvatar(),
  ],
)
```
<img width="25%" src="https://user-images.githubusercontent.com/8345062/114079401-73d2f700-98aa-11eb-9aa1-7351b12b4e44.png" alt="screenshot-2"></img>

To have some padding you have to add it yourself. Padding may be required in some use-cases but not in others. Therefore we can't add it by default to the `BackdropAppBar`.

**Comment by AjayrajSingh** [comment]
Okay, I got it. Thanks for the detailed explaination.
