### ISSUE TITLE
Add maintainState property to automatically clear state when backLayer is collapsed

### ISSUE THREAD

**Issue by ScottMacDougall** [fluttercommunity/backdrop#91]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to clear the state of the back layer when not visible, without manually having to clear the state. Example would be if there was a TextField in the back layer that I don't want to persist after back layer is collapsed.

**Describe the solution you'd like**
Many widgets in Flutter, such as ExpansionTile have a maintainState property to control this functionality.

**Describe alternatives you've considered**
Aside from manual cleanup, I can change the backLayer Widget conditionally based on whether the backLayer is visible or not.
`backLayer: _backdropOpen ? BackLayerWidget() : Container(),`

**Comment by daadu** [comment]
you could set a `GlobalKey` to `BackLayer` and change it when you want, that will "create new state" for backLayer.

**Comment by ScottMacDougall** [comment]
Definitely. The request is to simply provide a low-code way to handle this in a way developers may already be familiar with from using other widgets.

**Comment by WieFel** [comment]
Well I think we could add it. @ScottMacDougall maybe also you can try to implement it and open a PR? ;)

**Comment by ScottMacDougall** [comment]
Sure thing. I’ll try to get to it this week.

**Comment by daadu** [comment]
This fix/feature has landed with [v0.6.1 on pub.dev](https://pub.dev/packages/backdrop/versions/0.6.1).
