### ISSUE TITLE
Reveal backlayer with natural gestures

### ISSUE THREAD

**Issue by m-lecomte** [fluttercommunity/backdrop#92]
When I want to open backdrop, we have to click on the top left button. As a result, the navigation is no longer efficient in my opinion.

I wish I could slide down and reveal the backlayer, then slide up to close it. This is a natural gesture very appreciated, and available on natives android applications. So this could be implemented through an animation or with the coordinates of the touch events.

**Comment by WieFel** [comment]
We already had a similar issue about this in #68, so I think we won't integrate this into the package.

However, you might be able to achieve your desired behaviour by using a `GestureDetector` and passing a custom `AnimationController` to `BackdropScaffold`.
