### ISSUE TITLE
Make a parameter out of front layer elevation

### ISSUE THREAD

**Issue by hendrychjan** [fluttercommunity/backdrop#94]
Make font layer elevation a parameter, so that you can easily change the amount of shadow you want to have there.

I've discussed this with Felix (@WieFel) on gitter, he suggested that the elevation [here](https://github.com/fluttercommunity/backdrop/blob/7d59a0827dde60bd59a57450e161bb35e5f9acac/lib/scaffold.dart#L624) is set to "1", so maybe you could make it a parameter?

**Comment by daadu** [comment]
@hendrychjan Thank you for the suggestion.

Can you write the PR for this?

**Comment by hendrychjan** [comment]
Sure. How much is it urgent? Can I do it during the weekend?

**Comment by WieFel** [comment]
@hendrychjan sure, whenever you have time! ;)

**Comment by daadu** [comment]
The feature has landed on [pub.dev with v0.7.0](https://pub.dev/packages/backdrop/versions/0.7.0).

Thanks @hendrychjan for suggesting it, check yourself in project README!
