### ISSUE TITLE
Avoid SubHeader spawn on top of Front Layer

### ISSUE THREAD

**Issue by LorenzoVianello** [fluttercommunity/backdrop#97]
I'm using the plugin for a custom audio player, and subheader is suitable for minimized player, but every time i come back to front layer, the subheader sticks itself on the top, and at the moment i didn't figured out how to fix this, apart from using Obx block and map menu openings.

Is it already available as feature, am I doing something wrong or is still impossibile?

**Comment by WieFel** [comment]
Can you show a screenshot/gif and explain what you would expect, and what is going wrong in more detail?

**Comment by daadu** [comment]
Closing this because of lack of response. @LorenzoVianello Feel free to request to re-open.
