### ISSUE TITLE
Use AppBar.SystemOverlayStyle instead of AppBar.Brightness

### ISSUE THREAD

**Issue by pascalwild** [fluttercommunity/backdrop#98]
Would be great if you could migrate `AppBar.brightness` to `AppBar.systemOverlayStyle` because the property is no longer used.

**Comment by WieFel** [comment]
@pascalwild thanks for the input! And sorry for the delay.
I will have a look at this asap. If you are quicker, please go ahead and open a PR ;)

**Comment by daadu** [comment]
The feature has landed on [pub.dev with v0.7.0](https://pub.dev/packages/backdrop/versions/0.7.0).

Thanks @pascalwild for suggesting it, check yourself in project README!
